export enum FOLDER__NAME {
  JOB__THUMBNAIL = "JOB__THUMBNAIL",
  JOB__VIDEO = "JOB__VIDEO",
  VIDEO__INTERVIEW = "VIDEO__INTERVIEW",
  INTERVIEW_RESUMES = "INTERVIEW_RESUMES",
  USER_FEED_VIDEO = "USER_FEED_VIDEO",
  COMPANY__LOGO = "COMPANY__LOGO",
  COMPANY__COVER = "COMPANY__COVER",
  USER__COVER = "USER__COVER",
  USER__AVATAR = "USER__AVATAR",
  JOB__CATEGORIES__LOGO = "JOB__CATEGORIES__LOGO",
}
